spring:
  application:
    name: limit-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_limit?currentSchema=public
    username: test
    password: test

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web: INFO

user:
  default-limit: 10000
