spring:
  application:
    name: payment-service

server:
  port: 8080

integration:
  product-service:
    url: http://localhost:8081
  limit-service:
    url: http://localhost:8082

logging:
  level:
    org:
      springframework:
        web: INFO
